// Code generated by entc, DO NOT EDIT.

package ent

import (
	"template/ent/schema"
	"template/ent/template"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	templateFields := schema.Template{}.Fields()
	_ = templateFields
	// templateDescCreatedAt is the schema descriptor for createdAt field.
	templateDescCreatedAt := templateFields[2].Descriptor()
	// template.DefaultCreatedAt holds the default value on creation for the createdAt field.
	template.DefaultCreatedAt = templateDescCreatedAt.Default.(func() time.Time)
	// templateDescUpdatedAt is the schema descriptor for updatedAt field.
	templateDescUpdatedAt := templateFields[3].Descriptor()
	// template.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	template.DefaultUpdatedAt = templateDescUpdatedAt.Default.(func() time.Time)
	// template.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	template.UpdateDefaultUpdatedAt = templateDescUpdatedAt.UpdateDefault.(func() time.Time)
}
